#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleApp.Resource", IsApplication=true)]

namespace SampleApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int ListItem_Description = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int ListItem_Title = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int SampleItemListView = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int SampleItemListView_AddItemCommand = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int SampleItemListView_Items = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int SampleItemListView_RemoveItemCommand = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int SampleItemListView_ViewItemCommand = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int SampleItemView = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int SampleItemView_Description = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int SampleItemView_SaveCommand = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int SampleItemView_Title = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int tableRow1 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int tableRow2 = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SampleItemListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SampleItemView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
