#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CloudAuction.Resource", IsApplication=true)]

namespace CloudAuction
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Macaw.UIComponents.Resource.String.ApplicationName = global::CloudAuction.Resource.String.ApplicationName;
			global::Macaw.UIComponents.Resource.String.Hello = global::CloudAuction.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Checkmark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int magnify = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int slider_blt_grn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int slider_blt_trans = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int AuctionView = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int AuctionView_AvailableCount = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int AuctionView_Condition = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int AuctionView_CurrentPrice = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int AuctionView_Description = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int AuctionView_Image = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int AuctionView_Intro = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int AuctionView_ListPrice = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int AuctionView_Name = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int AuctionView_PlaceBidCommand = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int AuctionView_TimePercentageRemaining = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int AuctionView_TimeRemaining = 2131099658;
			
			// aapt resource value: 0x7f06002b
			public const int LogoutMenuItem = 2131099691;
			
			// aapt resource value: 0x7f06000c
			public const int MainView = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int MainView_TabFragmentContainer = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int OrderResultView = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int OrderResultView_DoneCommand = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int OrderResultView_Message = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int OrderView = 2131099666;
			
			// aapt resource value: 0x7f06001a
			public const int OrderView_City = 2131099674;
			
			// aapt resource value: 0x7f06001f
			public const int OrderView_ConfirmCommand = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int OrderView_Country = 2131099675;
			
			// aapt resource value: 0x7f060013
			public const int OrderView_DeliveryLocation = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int OrderView_Email = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int OrderView_FirstName = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int OrderView_LastName = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int OrderView_MiddleName = 2131099670;
			
			// aapt resource value: 0x7f06001d
			public const int OrderView_Mobile = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int OrderView_Phone = 2131099678;
			
			// aapt resource value: 0x7f060018
			public const int OrderView_Street = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int OrderView_Title = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int OrderView_Zip = 2131099673;
			
			// aapt resource value: 0x7f060021
			public const int ProductListItem_Description = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int ProductListItem_ListPrice = 2131099682;
			
			// aapt resource value: 0x7f060020
			public const int ProductListItem_Name = 2131099680;
			
			// aapt resource value: 0x7f060025
			public const int ProductView = 2131099685;
			
			// aapt resource value: 0x7f060028
			public const int ProductView_Description = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int ProductView_ListPrice = 2131099689;
			
			// aapt resource value: 0x7f060027
			public const int ProductView_Name = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int ProductView_ProductInfo = 2131099686;
			
			// aapt resource value: 0x7f060023
			public const int ProductsView = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int ProductsView_ProductList = 2131099684;
			
			// aapt resource value: 0x7f06002a
			public const int TextListItem = 2131099690;
			
			// aapt resource value: 0x7f06000f
			public const int imageView1 = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuctionView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OrderResultView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int OrderView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ProductListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ProductsView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ProductView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TextListItem = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Logout = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
